language: node_js
node_js:
  - "10"
install:
  - npm install -g mocha
  - npm install nyc --savedev
  - npm install -g codecov
script:
  - nyc npm test
  - nyc report --reporter=text-lcov > coverage.lcov
- codecov